# Generated by Django 4.2.6 on 2023-10-07 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_lecturer',
            field=models.BooleanField(default=False, help_text='designates whether the user is a lecturer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, help_text='designates whether the user is a student'),
        ),
    ]
