# Generated by Django 4.2.6 on 2023-10-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentqr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentQr',
        ),
    ]
