# Generated by Django 4.2.6 on 2023-10-09 06:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_studentqr'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQr',
            fields=[
                ('qr_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('registration_no', models.CharField(max_length=30, null=True)),
                ('qr_image', models.ImageField(upload_to='img/qr_code/')),
            ],
        ),
    ]
